version: '3.7'

services:

  app:
    image: nginx:1.20-alpine
    container_name: laravel-example-app
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/includes/cache.conf:/etc/nginx/includes/cache.conf
      - ./nginx/includes/php.conf:/etc/nginx/includes/php.conf
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./app:/app
    labels:
      traefik.enable: "true"
      traefik.http.routers.symfony-example-app.entrypoints: https
      traefik.http.routers.symfony-example-app.rule: Host(`laravel.docker.so`)
      traefik.http.routers.symfony-example-app.tls: "true"
      traefik.docker.network: stonehenge-network
    networks:
      - internal
      - stonehenge-network

  php-fpm:
    image: php:8.0-fpm-alpine
    container_name: symfony-example-php-fpm
    volumes:
      - ./app:/app
    networks:
      - internal

networks:
  internal:
    external: false
  stonehenge-network:
    external: true
