version: '3.7'

services:

  app:
    image: wordpress:latest
    container_name: "wordpress-example-app"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    labels:
      traefik.enable: "true"
      traefik.http.routers.wordpress-example-app.entrypoints: https
      traefik.http.routers.wordpress-example-app.rule: Host(`wordpress.docker.so`,`wordpress.traefik.me`)
      traefik.http.routers.wordpress-example-app.tls: "true"
      traefik.docker.network: stonehenge-network
    networks:
      - internal
      - stonehenge-network

  db:
    image: mysql:8.0
    container_name: "wordpress-example-db"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - internal

networks:
  internal:
    external: false
  stonehenge-network:
    external: true
